apiVersion: skaffold/v1alpha4
kind: Config
build:
  tagPolicy:
    dateTime: {}
  artifacts:
  - image: gcr.io/qingyangc-sandbox/skaffold-sub-jib
    context: .
    jibGradle:
      project: subhelloproject
  - image: gcr.io/qingyangc-sandbox/skaffold-jib
    context: .
    jibMaven: {}
#    sync:
#      '*.html': src/main/resources/public/
  local: {}
deploy:
  kubectl:
    manifests:
