apiVersion: skaffold/v1alpha4
kind: Config
build:
  tagPolicy:
    dateTime: {}
  artifacts:
  - image: gcr.io/qingyangc-sandbox/skaffold-jib-name-service
    context: .
    jibGradle:
      project: name-service
  - image: gcr.io/qingyangc-sandbox/skaffold-jib-hello-service
    context: .
    jibMaven: {}
  local: {}
deploy:
  kubectl:
    manifests:
