apiVersion: v1
kind: Service
metadata:
  labels:
    service: ambassador
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  frontend-service
      prefix: /
      service: frontend-service
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  vote-service
      prefix: /vote/
      service: vote-service
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  notification-service
      prefix: /subscribe
      service: notification-service
      use_websocket: true
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  prevent-notify
      prefix: /subscribe/notify
spec:
  type: LoadBalancer
  loadBalancerIP: 35.230.121.214
  ports:
  - name: ambassador
    port: 80
    targetPort: 80
  selector:
