apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: helloworld-sub
  name: helloworld-sub
spec:
  replicas: 1
  selector:
    matchLabels:
      run: helloworld-sub
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: helloworld-sub
    spec:
      containers:
      - image: gcr.io/qingyangc-sandbox/skaffold-sub-jib
        name: helloworld-sub
        ports:
        - containerPort: 5005
        - containerPort: 4567
        resources: {}
status: {}
