apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: helloworld-sub
  name: name-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4567
  selector:
    run: helloworld-sub
  type: ClusterIP
status:
  loadBalancer: {}
